name: Deploy Cloud Functions
on:
  # mainへのPush時、または手動でワークフローを実行する
  workflow_dispatch:
  push:
    branches: 
      - main
      - develop

jobs:
  job_id:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: "actions/checkout@v4"

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID}} # 作成したプロバイダのID
          service_account: "collector@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com" # プロバイダで指定したサービスアカウント

      - id: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v2"
        with: # Cloud Functions の設定(下記は一例)
          name: "function_sample3" # 関数名
          entry_point: "main" # エントリポイント
          runtime: "python311" # 関数に使うランタイム
          env_vars: ENV1=hogehoge, ENV2=fugafuga # 環境変数
          #source_dir: "cloud_functions" # ルートディレクトリに main.py が無い時はこれでディレクトリを指定する
          timeout: 120 # 関数のタイムアウト時間
          max_instances: 10 # 最大インスタンス数
          region: "asia-northeast1" # リージョン
